### ISSUE TITLE
locking?

### ISSUE THREAD

**Issue by typekpb** [syscrusher/fake#1]
not sure if it's an issue, but I've noticed locking in the lookup method: 

```
func lookup(lang, cat string, fallback bool) string {
    samplesLock.Lock()
    s := _lookup(lang, cat, fallback)
    samplesLock.Unlock()
    return s
}
```

does it mean it's kind of a synchronous access? If so, is there any chance to provide non-locking implementation? As for the parallel world it sounds like a bad idea.

**Comment by syscrusher** [comment]
The sample data gets cached in a map, and maps are not safe for concurrent access in Go. We need to coordinate access, and a mutex is probably the appropriate solution.
However, we should be using a RWMutex so that once it is cached then readers can access it concurrently. Commit 9d352d2 does that.
Thanks for the report!

**Comment by typekpb** [comment]
thanks for incredible response time!
